require_relative 'ast/assignment'
require_relative 'ast/call'
require_relative 'ast/comment'
require_relative 'ast/delay_stmt'
require_relative 'ast/if'
require_relative 'ast/jump'
require_relative 'ast/label'
require_relative 'ast/offset_condition_stmt'
require_relative 'ast/override_stmt'
require_relative 'ast/payload_stmt'
require_relative 'ast/program'
require_relative 'ast/remark'
require_relative 'ast/rsr_stmt'
require_relative 'ast/run'
require_relative 'ast/select_case'
require_relative 'ast/select_else'
require_relative 'ast/select_stmt'
require_relative 'ast/skip_stmt'
require_relative 'ast/statement'
require_relative 'ast/stop_tracking_stmt'
require_relative 'ast/ualm_stmt'
require_relative 'ast/wait_stmt'

module TP
  module AST ; end
end
